# Import FastAPI and HTTPException from the fastapi module
from fastapi import FastAPI, HTTPException

# Create an instance of the FastAPI class
app = FastAPI()

# GET endpoint that returns a simple message
@app.get("/test")
def test():
    return {"message": "Hello, World!"}


# GET endpoint that adds two numbers and returns the result
@app.get("/add")
def add_endpoint(x: int, y: int) -> int:
    return x + y



"""
In GET data is sent in the URL as query parameters, while in POST data is sent in the request body.
"""


# Import BaseModel, Field, EmailStr, and HttpUrl from pydantic module for data validation and serialization
from pydantic import BaseModel, Field, EmailStr, HttpUrl
from datetime import date

# Define a Pydantic model for an item with fields for name, description, price, and tax
class Item(BaseModel):
    name: str
    description: str = None
    price: float
    tax: float = None


# Define a POST endpoint that accepts an Item object and returns it
# Item object is automatically validated and serialized by FastAPI using the Pydantic model
@app.post("/items/")
def create_item(item: Item):
    return item






# Define a Pydantic model for a user with fields for username, email, age, GitHub URL, enrolled date, full name, and skills
# Here we are also validating the fields using Pydantic's Field, EmailStr, and HttpUrl types
# for example, username must be between 3 and 50 characters, age must be greater than zero, and skills must contain at least one skill
# email must be a valid email address, and github_url must be a valid URL
class User(BaseModel):
    username: str = Field(min_length=3, max_length=50)
    email: str = EmailStr
    age: int = Field(gt=0, description="Age must be greater than zero")
    github_url: str = HttpUrl
    enrolled_date: str = date
    full_name: str = None
    skills: list[str] = Field(min_length=1, max_length=10, description="Skills must contain at least one skill")


# Define a POST endpoint that accepts a User object and returns it
@app.post("/users/")
def create_user(user: User):
    return {"user": user}   





# Create a dictionary to store book data with book IDs as keys and book details as values
books= {
    1:{
        "id": 1,
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "price": 10.99
    },
    2:{
        "id": 2,
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",                 
        "price": 12.99
    },
    3:{
        "id": 3,
        "title": "1984",
        "author": "George Orwell",
        "price": 9.99
    }
}


# Define a Pydantic model for a book with fields for title, author, and price
class Book(BaseModel):
    title: str
    author: str
    price: float


# Define a POST endpoint that accepts a Book object and creates a new book entry in the books dictionary
# The new book ID is generated by finding the maximum existing book ID and adding 1 to it
@app.post("/books/")
def create_book(book: Book):
    new_id = max(books.keys()) + 1
    books[new_id] = {
        "id": new_id,
        "title": book.title,
        "author": book.author,
        "price": book.price
    }
    return "Book created successfully", "Book ID: {new_id}"



# Define a GET endpoint that retrieves a book by its ID from the books dictionary
# Here we are using path parameters to specify the book ID in the URL
@app.get("/books/{book_id}")
def get_book(book_id: int):
    if book_id in books:
        return books[book_id]
    else:
        return {"error": "Book not found"}, 404





# Define a PUT endpoint that replaces an existing book entry in the books dictionary with a new Book object
# PUT is used to update the entire resource, so we are replacing the existing book entry with the new one
@app.put("/books/{book_id}")
def replace_book(book_id: int, book: Book):
    if book_id in books:
        books[book_id]["title"] = book.title
        books[book_id]["author"] = book.author
        books[book_id]["price"] = book.price
        return "Book updated successfully"
    else:
        return {"error": "Book not found"}, 404






# Define a Pydantic model for updating a book with optional fields for title, author, and price
# Here we are using Optional type hints to indicate that these fields can be None if not provided
from typing import Optional
class BookUpdate(BaseModel):
    title: Optional[str] = None
    author: Optional[str] = None
    price: Optional[float] = None


# Define a PATCH endpoint that updates an existing book entry in the books dictionary with the provided BookUpdate object
# PATCH is used to update only the specified fields of the resource, so we are updating only the fields that are provided in the request body
@app.patch("/books/{book_id}")
def update_book(book_id: int, book: BookUpdate):
    if book_id not in books:
        raise HTTPException(status_code=404, detail="Book not found")
    update_data = book.model_dump(exclude_unset=True)
    books[book_id].update(update_data)
    return {"message": "Book updated successfully", "book": books[book_id]}





# Define a DELETE endpoint that removes an existing book entry from the books dictionary by its ID
@app.delete("/books/{book_id}")
def delete_book(book_id: int):
    if book_id in books:
        del books[book_id]
        return {"message": "Book deleted successfully"}
    else:
        raise HTTPException(status_code=404, detail="Book not found")




    

    